services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=my_org
      - DOCKER_INFLUXDB_INIT_BUCKET=my_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123
    restart: unless-stopped

  telegraf2:
    image: telegraf:latest
    container_name: telegraf2
    restart: unless-stopped
    environment:
      - TELEGRAF_CONFIG_PATH=/etc/telegraf2/telegraf.conf
    volumes:
      - ./telegraf2/telegraf2.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - mosquitto
      - influxdb
    links:
      - influxdb
      - mosquitto

volumes:
  influxdb_data: